spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack_db
    username: fintrack_user
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    enabled: true
    certificate: classpath:ssl/localhost.pem
    certificate-private-key: classpath:ssl/localhost-key.pem

app:
  jwt:
    secret: your_dev_jwt_secret_keySDGAIOWRAOKSGIOSDAHGKJASDJGHSDAKJGTHSDIUAGHISDG
    expiration: 3600000
    refresh-expiration: 86400000
    issuer: https://localhost:8443
    audience: https://localhost:3000